### ISSUE TITLE
Add meta tags to website

### ISSUE THREAD

**Issue by jorgerodrigues** [jorgerodrigues/PersonalPage#5]
- [x] Meta tags main layout
- [x] Meta tags post page
- [x] Meta tags about page
- [x] Meta tags portfolio page
